default: &default
  adapter: postgresql
  database: tomy8s
  username: postgres
  password: Password
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: tomy8s
  host: localhost
  username: postgres
  password: Password
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: tomy8s_test
  username: postgres
  password: Password
  pool: 5
  timeout: 5000
  
production:
  <<: *default
