# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f99c845ead1f4d59d91f7f93259ec45a534b078d8a23967a5dd65301ff4e3b973a6ff5b739f1df91f067676a4263ce9567e30aa502c1e19123950938175238ef

test:
  secret_key_base: 8549cfe8a59a66ac12d3379b36ec236aad9448f750645c471e617e3420024ff89452d3edafd1d28abb8f26a079842a4c4603b2d53b8c3dedf2708af2850db78c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
